version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: goe_user
      POSTGRES_PASSWORD: goe_password
      POSTGRES_DB: GOEDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goe_user -d GOEDB"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DEFAULT_CONNECTION=Host=postgres;Port=5432;Database=GOEDB;Username=goe_user;Password=goe_password
    ports:
      - "8080:80"

volumes:
  postgres_data:
