version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: goe_db
    restart: always
    environment:
      POSTGRES_DB: goe_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goe_api
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=goe_ecommerce;Username=postgres;Password=postgres"
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/app
    command: ["dotnet", "run", "--project", "src/Presentation"]

volumes:
  postgres_data:
